spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmed-ramsey-shahin/TodoList/
          search-paths:
          - configuration/userservice
          - configuration/todoservice
          - configuration/discoveryservice
          timeout: 5
          clone-on-start: true
          default-label: main
        encrypt:
          enabled: false
